// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjx1KsBYsdYGliprXNlqjbQfbbYaMTxuQ',
    appId: '1:842493668263:web:450109ee7d993a2f18e482',
    messagingSenderId: '842493668263',
    projectId: 'fir-trial-90403',
    authDomain: 'fir-trial-90403.firebaseapp.com',
    storageBucket: 'fir-trial-90403.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNoPF8SXQoqxVHA4JUPab0D_jc9eb23U',
    appId: '1:842493668263:android:2c8284bae6a0f1ba18e482',
    messagingSenderId: '842493668263',
    projectId: 'fir-trial-90403',
    storageBucket: 'fir-trial-90403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvDRz04Si-SijKF7pn8fdX0Da2d9EsQc',
    appId: '1:842493668263:ios:f3f2223f9a2f12b818e482',
    messagingSenderId: '842493668263',
    projectId: 'fir-trial-90403',
    storageBucket: 'fir-trial-90403.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANvDRz04Si-SijKF7pn8fdX0Da2d9EsQc',
    appId: '1:842493668263:ios:f3f2223f9a2f12b818e482',
    messagingSenderId: '842493668263',
    projectId: 'fir-trial-90403',
    storageBucket: 'fir-trial-90403.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );
}
